server:
  port: 8190
  servlet:
    context-path: /store-cart


integrations:
  product-service:
    url: http://localhost:8090/store-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

cart-service:
  cart-prefix: myStore-cart