server:
  port: 8090
  servlet:
    context-path: /store-core

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/CORE
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  cart-service:
    url: http://localhost:8190/store-cart/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000